# Copyright 2011 <chaishushan@gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARGS:=\
	edge\
	inpaint

include ./Make.samples

